# See https://docs.acquia.com/acquia-cloud/develop/pipelines/yaml/ for docs.
version: 1.0.0
services:
  - php:
      version: 5.6
variables:
  global:
    ENV: pipelines
events:
  build:
    steps:
      # Deploy the build artifact to a Cloud on-demand environment.
      - deploy:
          script:
            # Only create ODE for feature branches.
            - if [[ "$SOURCE_VCS_PATH" =~ ^feature\/.+$ ]]; then pipelines-deploy ;fi
  # When a GitHub pull request is merged, this deletes the coresponding On Demand Environment.
  pr-merged:
    steps:
      - deploy:
          script:
            -  pipelines-deploy
  # When a GitHub pull request is closed, this deletes the coresponding On Demand Environment.
  pr-closed:
    steps:
      - deploy:
          script:
            - pipelines-deploy