project:
  name: myhaccp
  file_sync_url: https://myhaccp.fsa.prod.wunder.io
ansible:
  remote: git@github.com:wunderio/WunderMachina.git
  branch: master 
  revision:
buildsh:
  enabled: true
  branch: master
  revision:
wundertools:
  branch: master
externaldrupal:
  remote:
  branch:
  location:
drush:
  alias_path: drupal/drush
wundersecrets:
  remote: git@github.com:wunderio/WunderSecrets.git

