<?php
/**
 * @file
 */

/**
 * Implements hook_form_alter().
 */
function myhaccp_language_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_register_form' || $form_id == 'user_profile_form') {
    // Use exactly the same access logic as the original,
    // without checking for the 'administer users' permission.
    $form['locale']['#access'] = ($form['#user_category'] == 'account' || ($form['#user_category'] == 'register'));
    $form['locale']['#type'] = 'container';
   // $form['locale']['#weight'] = 0;
   // $form['locale']['language']['#title'] = t('Picka Language');
  }
}