<?php
/**
 * @file
 * Install, update and uninstall functions for the MyHACCP installation profile.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function myhaccp_install() {
  
  // Enable themes
  $themes = array(
    'theme_default' => 'myhaccp_theme',
    'admin_theme' => 'adminimal',
  );
  theme_enable($themes);

  // Disable the default Bartik theme
  theme_disable(array('bartik'));
}
