---
# Example site.yml

# The default environment is our local development environment.
# Note that the the default site is used as a base for all sites, so whatever you define here are inherited to
# other site definitions.
default:

  # An alias or aliases for the site, this could also be:
  # aliases:
  #   - vagrant
  #   - mylocalbox
  aliases:
    - vagrant
    - local

  # The drush make file to use
  makefile: conf/site.make

  # Directory used to build the site
  temporary: _build

  make_cache: .make_cache

  # The final produced Drupal installation
  final: web

  # Directory which will house all the previous builds
  previous: builds

  # Installation profile to use
  profile: myhaccp

  # Site name given at installation phase
  site: MyHACCP

  # In development environments we usually want to use symlinks, note the settings.php linking
  link:
    - files: sites/default/files

  local_commands:
    update:
      - shell: ln -s files web/sites/default/files
      - finalize
      - update
      - drush: en stage_file_proxy -y
      - shell: sudo systemctl restart nginx php-fpm memcached varnish
      - cleanup


# Production environment:
production:

  aliases: prod

  # Prod environment only symlinks files
  link:
    - /var/www/myhaccp.fsa.prod.wunder.io/files: sites/default/files

  local_commands:
    build:
      - shell: ln -s /var/www/myhaccp.fsa.prod.wunder.io/files web/sites/default/files
      - shell: chmod -R a-w web

    update:
      - update
      - shell: sudo systemctl restart nginx php-fpm memcached varnish
      - cleanup

